server:
  publicAddr: 0.0.0.0:9847
  privateAddr: 0.0.0.0:9848

mq:
  type: nsq
  nsqdAddr: 124.221.243.128:4150

thirdService:
  identifyServiceAddr: http://124.221.243.128:9500

db:
  user: root
  passwd: 12345678
  host: 127.0.0.1
  port: 3306
  dbName: message_push

event:
  topics:
    - core.users.notify
    - test01
    - test02